spring:
  datasource:
    url: jdbc:mariadb://172.17.0.1:3306/app33_prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: lldjlocal
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
custom:
  genFileDirPath: /storage/app33